version: 2

jobs:
    "python-3.6": &test-template
        docker:
            - image: circleci/python:3.6-stretch-node-browsers

        environment:
            PERCY_ENABLE: 0

        steps:
            - checkout

            - run:
                name: Write job name.
                command: echo $CIRCLE_JOB > circlejob.txt

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

            - run:
                name: Create virtualenv
                command: |
                    sudo pip install virtualenv
                    python -m venv venv || virtualenv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - "venv"

            - run:
                name: Generations tests
                command: |
                    . venv/bin/activate
                    pytest tests --driver Chrome
                when: always

    "python-2.7":
        <<: *test-template
        docker:
            - image: circleci/python:2.7-stretch-node-browsers


workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
            - "python-2.7"
